name: Continuous Integration

on:
  push:
    branches:
      - endpoint-testcases

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Start Server
        run: |
          python3 start_server.py > /dev/null 2>&1 &
          sleep 30

      - name: Run tests and generate coverage report
        run: |
          pytest -vv --disable-warnings --cov=app --cov-report=xml || true
